services:
  - type: web
    name: halawani-clinic
    runtime: node
    plan: free
    buildCommand: |
      if [ -f "src/index.html" ]; then mv src/index.html .; fi
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: halawani_data
      mountPath: /data
      sizeGB: 1
